name: flutter_yoga_animation
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  gradient_slide_to_act: ^0.0.2
  # slide_to_act: ^2.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/character-2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: UbuntuBold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
    - family: UbuntuMedium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
    - family: UbuntuRegular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: UbuntuLight
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
